package org.sorapointa.proto;
import io.github.sainttheana.proto.core.Tag;
import java.util.List;
import java.util.ArrayList;

public enum AbilityInvokeArgument {
        @Tag(tag=0) AbilityNone ,
        @Tag(tag=1) AbilityMetaModifierChange ,
        @Tag(tag=2) AbilityMetaCommandModifierChangeRequest ,
        @Tag(tag=3) AbilityMetaSpecialFloatArgument ,
        @Tag(tag=4) AbilityMetaOverrideParam ,
        @Tag(tag=5) AbilityMetaClearOverrideParam ,
        @Tag(tag=6) AbilityMetaReinitOverridemap ,
        @Tag(tag=7) AbilityMetaGlobalFloatValue ,
        @Tag(tag=8) AbilityMetaClearGlobalFloatValue ,
        @Tag(tag=9) AbilityMetaAbilityElementStrength ,
        @Tag(tag=10) AbilityMetaAddOrGetAbilityAndTrigger ,
        @Tag(tag=11) AbilityMetaSetKilledSetate ,
        @Tag(tag=12) AbilityMetaSetAbilityTrigger ,
        @Tag(tag=13) AbilityMetaAddNewAbility ,
        @Tag(tag=14) AbilityMetaRemoveAbility ,
        @Tag(tag=15) AbilityMetaSetModifierApplyEntity ,
        @Tag(tag=16) AbilityMetaModifierDurabilityChange ,
        @Tag(tag=17) AbilityMetaElementReactionVisual ,
        @Tag(tag=18) AbilityMetaSetPoseParameter ,
        @Tag(tag=19) AbilityMetaUpdateBaseReactionDamage ,
        @Tag(tag=20) AbilityMetaTriggerElementReaction ,
        @Tag(tag=21) AbilityMetaLoseHp ,
        @Tag(tag=22) AbilityMetaDurabilityIsZero ,
        @Tag(tag=50) AbilityActionTriggerAbility ,
        @Tag(tag=51) AbilityActionSetCrashDamage ,
        @Tag(tag=52) AbilityActionEffect ,
        @Tag(tag=53) AbilityActionSummon ,
        @Tag(tag=54) AbilityActionBlink ,
        @Tag(tag=55) AbilityActionCreateGadget ,
        @Tag(tag=56) AbilityActionApplyLevelModifier ,
        @Tag(tag=57) AbilityActionGenerateElemBall ,
        @Tag(tag=58) AbilityActionSetRandomOverrideMapValue ,
        @Tag(tag=59) AbilityActionServerMonsterLog ,
        @Tag(tag=60) AbilityActionCreateTile ,
        @Tag(tag=61) AbilityActionDestroyTile ,
        @Tag(tag=62) AbilityActionFireAfterImage ,
        @Tag(tag=63) AbilityActionDeductStamina ,
        @Tag(tag=64) AbilityActionHitEffect ,
        @Tag(tag=65) AbilityActionSetBulletTrackTarget ,
        @Tag(tag=66) GHKNBDBFGLN ,
        @Tag(tag=100) AbilityMixinAvatarSteerByCamera ,
        @Tag(tag=101) AbilityMixinMonsterDefend ,
        @Tag(tag=102) AbilityMixinWindZone ,
        @Tag(tag=103) AbilityMixinCostStamina ,
        @Tag(tag=104) AbilityMixinEliteShield ,
        @Tag(tag=105) AbilityMixinElementShield ,
        @Tag(tag=106) AbilityMixinGlobalShield ,
        @Tag(tag=107) AbilityMixinShieldBar ,
        @Tag(tag=108) AbilityMixinWindSeedSpawner ,
        @Tag(tag=109) AbilityMixinDoActionByElementReaction ,
        @Tag(tag=110) AbilityMixinFieldEntityCountChange ,
        @Tag(tag=111) AbilityMixinScenePropSync ,
        @Tag(tag=112) AbilityMixinWidgetMpSupport ,
        @Tag(tag=113) AbilityMixinDoActionBySelfModifierElementDurabilityRatio ,
        @Tag(tag=114) AbilityMixinFireworksLauncher ,
        @Tag(tag=115) AbilityMixinAttackResultCreateCount ,
        @Tag(tag=116) AbilityMixinUgcTimeControl ,
        @Tag(tag=117) AbilityMixinAvatarCombat ,
        @Tag(tag=118) AbilityMixinDeathZoneRegionalPlayMixin ,
        @Tag(tag=119) AbilityMixinUiInteract ,
        @Tag(tag=120) AbilityMixinShootFromCamera ,
        @Tag(tag=121) AbilityMixinEraseBrickActivity ,
        @Tag(tag=122) AbilityMixinBreakout ,
        @Tag(tag=123) BFBGAADHEJC ,
        @Tag(tag=124) HGOJHAPAJLD ;
}
