package org.sorapointa.proto;
import io.github.sainttheana.proto.core.Tag;
import java.util.List;
import java.util.ArrayList;
import org.sorapointa.proto.ActivityPushTipsData.*;
import org.sorapointa.proto.ActivityPushTipsData;
import org.sorapointa.proto.ActivityWatcherInfo.*;
import org.sorapointa.proto.ActivityWatcherInfo;
import org.sorapointa.proto.ArenaChallengeActivityDetailInfo.*;
import org.sorapointa.proto.ArenaChallengeActivityDetailInfo;
import org.sorapointa.proto.AsterActivityDetailInfo.*;
import org.sorapointa.proto.AsterActivityDetailInfo;
import org.sorapointa.proto.BartenderActivityDetailInfo.*;
import org.sorapointa.proto.BartenderActivityDetailInfo;
import org.sorapointa.proto.BlessingActivityDetailInfo.*;
import org.sorapointa.proto.BlessingActivityDetailInfo;
import org.sorapointa.proto.BlitzRushActivityDetailInfo.*;
import org.sorapointa.proto.BlitzRushActivityDetailInfo;
import org.sorapointa.proto.BounceConjuringActivityDetailInfo.*;
import org.sorapointa.proto.BounceConjuringActivityDetailInfo;
import org.sorapointa.proto.BuoyantCombatDetailInfo.*;
import org.sorapointa.proto.BuoyantCombatDetailInfo;
import org.sorapointa.proto.ChannelerSlabActivityDetailInfo.*;
import org.sorapointa.proto.ChannelerSlabActivityDetailInfo;
import org.sorapointa.proto.CharAmusementDetailInfo.*;
import org.sorapointa.proto.CharAmusementDetailInfo;
import org.sorapointa.proto.ChessActivityDetailInfo.*;
import org.sorapointa.proto.ChessActivityDetailInfo;
import org.sorapointa.proto.CrucibleActivityDetailInfo.*;
import org.sorapointa.proto.CrucibleActivityDetailInfo;
import org.sorapointa.proto.CrystalLinkActivityDetailInfo.*;
import org.sorapointa.proto.CrystalLinkActivityDetailInfo;
import org.sorapointa.proto.DeliveryActivityDetailInfo.*;
import org.sorapointa.proto.DeliveryActivityDetailInfo;
import org.sorapointa.proto.DigActivityDetailInfo.*;
import org.sorapointa.proto.DigActivityDetailInfo;
import org.sorapointa.proto.DragonSpineActivityDetailInfo.*;
import org.sorapointa.proto.DragonSpineActivityDetailInfo;
import org.sorapointa.proto.EchoShellDetailInfo.*;
import org.sorapointa.proto.EchoShellDetailInfo;
import org.sorapointa.proto.EffigyActivityDetailInfo.*;
import org.sorapointa.proto.EffigyActivityDetailInfo;
import org.sorapointa.proto.EffigyChallengeV2DetailInfo.*;
import org.sorapointa.proto.EffigyChallengeV2DetailInfo;
import org.sorapointa.proto.ExpeditionActivityDetailInfo.*;
import org.sorapointa.proto.ExpeditionActivityDetailInfo;
import org.sorapointa.proto.FindHilichurlDetailInfo.*;
import org.sorapointa.proto.FindHilichurlDetailInfo;
import org.sorapointa.proto.FleurFairActivityDetailInfo.*;
import org.sorapointa.proto.FleurFairActivityDetailInfo;
import org.sorapointa.proto.FlightActivityDetailInfo.*;
import org.sorapointa.proto.FlightActivityDetailInfo;
import org.sorapointa.proto.FungusFighterDetailInfo.*;
import org.sorapointa.proto.FungusFighterDetailInfo;
import org.sorapointa.proto.GachaActivityDetailInfo.*;
import org.sorapointa.proto.GachaActivityDetailInfo;
import org.sorapointa.proto.GearActivityDetailInfo.*;
import org.sorapointa.proto.GearActivityDetailInfo;
import org.sorapointa.proto.GravenInnocenceDetailInfo.*;
import org.sorapointa.proto.GravenInnocenceDetailInfo;
import org.sorapointa.proto.HachiActivityDetailInfo.*;
import org.sorapointa.proto.HachiActivityDetailInfo;
import org.sorapointa.proto.HideAndSeekActivityDetailInfo.*;
import org.sorapointa.proto.HideAndSeekActivityDetailInfo;
import org.sorapointa.proto.InstableSprayDetailInfo.*;
import org.sorapointa.proto.InstableSprayDetailInfo;
import org.sorapointa.proto.IrodoriActivityDetailInfo.*;
import org.sorapointa.proto.IrodoriActivityDetailInfo;
import org.sorapointa.proto.IslandPartyDetailInfo.*;
import org.sorapointa.proto.IslandPartyDetailInfo;
import org.sorapointa.proto.LanternRiteActivityDetailInfo.*;
import org.sorapointa.proto.LanternRiteActivityDetailInfo;
import org.sorapointa.proto.LuminanceStoneChallengeActivityDetailInfo.*;
import org.sorapointa.proto.LuminanceStoneChallengeActivityDetailInfo;
import org.sorapointa.proto.LunaRiteDetailInfo.*;
import org.sorapointa.proto.LunaRiteDetailInfo;
import org.sorapointa.proto.MichiaeMatsuriActivityDetailInfo.*;
import org.sorapointa.proto.MichiaeMatsuriActivityDetailInfo;
import org.sorapointa.proto.MistTrialActivityDetailInfo.*;
import org.sorapointa.proto.MistTrialActivityDetailInfo;
import org.sorapointa.proto.MoonfinTrialActivityDetailInfo.*;
import org.sorapointa.proto.MoonfinTrialActivityDetailInfo;
import org.sorapointa.proto.MuqadasPotionActivityDetailInfo.*;
import org.sorapointa.proto.MuqadasPotionActivityDetailInfo;
import org.sorapointa.proto.MusicGameActivityDetailInfo.*;
import org.sorapointa.proto.MusicGameActivityDetailInfo;
import org.sorapointa.proto.PhotoActivityDetailInfo.*;
import org.sorapointa.proto.PhotoActivityDetailInfo;
import org.sorapointa.proto.PlantFlowerActivityDetailInfo.*;
import org.sorapointa.proto.PlantFlowerActivityDetailInfo;
import org.sorapointa.proto.PotionActivityDetailInfo.*;
import org.sorapointa.proto.PotionActivityDetailInfo;
import org.sorapointa.proto.RockBoardExploreDetailInfo.*;
import org.sorapointa.proto.RockBoardExploreDetailInfo;
import org.sorapointa.proto.RogueDiaryActivityDetailInfo.*;
import org.sorapointa.proto.RogueDiaryActivityDetailInfo;
import org.sorapointa.proto.RoguelikeDungeonActivityDetailInfo.*;
import org.sorapointa.proto.RoguelikeDungeonActivityDetailInfo;
import org.sorapointa.proto.SalesmanActivityDetailInfo.*;
import org.sorapointa.proto.SalesmanActivityDetailInfo;
import org.sorapointa.proto.SeaLampActivityDetailInfo.*;
import org.sorapointa.proto.SeaLampActivityDetailInfo;
import org.sorapointa.proto.SeaLampActivityInfo.*;
import org.sorapointa.proto.SeaLampActivityInfo;
import org.sorapointa.proto.SpiceActivityDetailInfo.*;
import org.sorapointa.proto.SpiceActivityDetailInfo;
import org.sorapointa.proto.SummerTimeDetailInfo.*;
import org.sorapointa.proto.SummerTimeDetailInfo;
import org.sorapointa.proto.SummerTimeV2DetailInfo.*;
import org.sorapointa.proto.SummerTimeV2DetailInfo;
import org.sorapointa.proto.SumoActivityDetailInfo.*;
import org.sorapointa.proto.SumoActivityDetailInfo;
import org.sorapointa.proto.TanukiTravelActivityDetailInfo.*;
import org.sorapointa.proto.TanukiTravelActivityDetailInfo;
import org.sorapointa.proto.TreasureMapActivityDetailInfo.*;
import org.sorapointa.proto.TreasureMapActivityDetailInfo;
import org.sorapointa.proto.TreasureSeelieActivityDetailInfo.*;
import org.sorapointa.proto.TreasureSeelieActivityDetailInfo;
import org.sorapointa.proto.TrialAvatarActivityDetailInfo.*;
import org.sorapointa.proto.TrialAvatarActivityDetailInfo;
import org.sorapointa.proto.UgcActivityDetailInfo.*;
import org.sorapointa.proto.UgcActivityDetailInfo;
import org.sorapointa.proto.VintageActivityDetailInfo.*;
import org.sorapointa.proto.VintageActivityDetailInfo;
import org.sorapointa.proto.WaterSpiritActivityDetailInfo.*;
import org.sorapointa.proto.WaterSpiritActivityDetailInfo;
import org.sorapointa.proto.WindFieldDetailInfo.*;
import org.sorapointa.proto.WindFieldDetailInfo;
import org.sorapointa.proto.WinterCampActivityDetailInfo.*;
import org.sorapointa.proto.WinterCampActivityDetailInfo;

public class ActivityInfo {
    public static class MapActivityCoinMap {
        @Tag(tag=1) public Integer key = null;
        @Tag(tag=2) public Integer value = null;
    }

    public static class MapWishGiftNumMap {
        @Tag(tag=1) public Integer key = null;
        @Tag(tag=2) public Integer value = null;
    }

    @Tag(tag=6) public Boolean isFinished = null;
    @Tag(tag=4) public Integer activityType = null;
    @Tag(tag=8) public Integer beginTime = null;
    @Tag(tag=329) public List<Integer> takenRewardList = new ArrayList<>();
    @Tag(tag=919) public Boolean isHidden = null;
    @Tag(tag=1449) public Boolean isQuickOpen = null;
    @Tag(tag=10) public List<Integer> meetCondList = new ArrayList<>();
    @Tag(tag=682) public List<MapActivityCoinMap> activityCoinMap = new ArrayList<>();
    @Tag(tag=102) public Boolean isBannerCleared = null;
    @Tag(tag=1906) public Integer curScore = null;
    @Tag(tag=592) public Integer firstDayStartTime = null;
    @Tag(tag=12) public Integer activityId = null;
    @Tag(tag=13) public Boolean isPlayOpenAnim = null;
    @Tag(tag=5) public Integer endTime = null;
    @Tag(tag=1958) public Integer scoreLimit = null;
    @Tag(tag=1399) public List<MapWishGiftNumMap> wishGiftNumMap = new ArrayList<>();
    @Tag(tag=1290) public Integer selectedAvatarRewardId = null;
    @Tag(tag=1963) public Boolean isCommonContentClosed = null;
    @Tag(tag=3) public List<Integer> expireCondList = new ArrayList<>();
    @Tag(tag=864) public List<ActivityPushTipsData> activityPushTipsDataList = new ArrayList<>();
    @Tag(tag=2) public List<ActivityWatcherInfo> watcherInfoList = new ArrayList<>();
    @Tag(tag=15) public Integer scheduleId = null;
    @Tag(tag=9) public Boolean isStarting = null;
    @Tag(tag=7) public SeaLampActivityDetailInfo samLampInfo = null;
    @Tag(tag=14) public CrucibleActivityDetailInfo crucibleInfo = null;
    @Tag(tag=11) public SalesmanActivityDetailInfo salesmanInfo = null;
    @Tag(tag=1) public TrialAvatarActivityDetailInfo trialAvatarInfo = null;
    @Tag(tag=1092) public DeliveryActivityDetailInfo deliveryInfo = null;
    @Tag(tag=557) public AsterActivityDetailInfo asterInfo = null;
    @Tag(tag=1365) public FlightActivityDetailInfo flightInfo = null;
    @Tag(tag=1727) public DragonSpineActivityDetailInfo dragonSpineInfo = null;
    @Tag(tag=391) public EffigyActivityDetailInfo effigyInfo = null;
    @Tag(tag=1114) public TreasureMapActivityDetailInfo treasureMapInfo = null;
    @Tag(tag=1869) public BlessingActivityDetailInfo blessingInfo = null;
    @Tag(tag=494) public SeaLampActivityInfo seaLampInfo = null;
    @Tag(tag=202) public ExpeditionActivityDetailInfo expeditionInfo = null;
    @Tag(tag=859) public ArenaChallengeActivityDetailInfo arenaChallengeInfo = null;
    @Tag(tag=857) public FleurFairActivityDetailInfo fleurFairInfo = null;
    @Tag(tag=1675) public WaterSpiritActivityDetailInfo waterSpiritInfo = null;
    @Tag(tag=1015) public ChannelerSlabActivityDetailInfo channelerSlabInfo = null;
    @Tag(tag=156) public MistTrialActivityDetailInfo mistTrialActivityInfo = null;
    @Tag(tag=427) public HideAndSeekActivityDetailInfo hideAndSeekInfo = null;
    @Tag(tag=1411) public FindHilichurlDetailInfo findHilichurlInfo = null;
    @Tag(tag=1372) public SummerTimeDetailInfo summerTimeInfo = null;
    @Tag(tag=1842) public BuoyantCombatDetailInfo buoyantCombatInfo = null;
    @Tag(tag=1113) public EchoShellDetailInfo echoShellInfo = null;
    @Tag(tag=767) public BounceConjuringActivityDetailInfo bounceConjuringInfo = null;
    @Tag(tag=794) public BlitzRushActivityDetailInfo blitzRushInfo = null;
    @Tag(tag=927) public ChessActivityDetailInfo chessInfo = null;
    @Tag(tag=1261) public SumoActivityDetailInfo sumoInfo = null;
    @Tag(tag=1588) public MoonfinTrialActivityDetailInfo moonfinTrialInfo = null;
    @Tag(tag=814) public LunaRiteDetailInfo lunaRiteInfo = null;
    @Tag(tag=54) public PlantFlowerActivityDetailInfo plantFlowerInfo = null;
    @Tag(tag=460) public MusicGameActivityDetailInfo musicGameInfo = null;
    @Tag(tag=219) public RoguelikeDungeonActivityDetailInfo roguelikeDungeonInfo = null;
    @Tag(tag=403) public DigActivityDetailInfo digInfo = null;
    @Tag(tag=491) public HachiActivityDetailInfo hachiInfo = null;
    @Tag(tag=1083) public WinterCampActivityDetailInfo winterCampInfo = null;
    @Tag(tag=1273) public PotionActivityDetailInfo potionInfo = null;
    @Tag(tag=1796) public TanukiTravelActivityDetailInfo tanukiTravelActivityInfo = null;
    @Tag(tag=1876) public LanternRiteActivityDetailInfo lanternRiteActivityInfo = null;
    @Tag(tag=194) public MichiaeMatsuriActivityDetailInfo michiaeMatsuriInfo = null;
    @Tag(tag=1725) public BartenderActivityDetailInfo bartenderInfo = null;
    @Tag(tag=703) public UgcActivityDetailInfo ugcInfo = null;
    @Tag(tag=1226) public CrystalLinkActivityDetailInfo crystalLinkInfo = null;
    @Tag(tag=750) public IrodoriActivityDetailInfo irodoriInfo = null;
    @Tag(tag=328) public PhotoActivityDetailInfo photoInfo = null;
    @Tag(tag=1891) public SpiceActivityDetailInfo spiceInfo = null;
    @Tag(tag=825) public GachaActivityDetailInfo gachaInfo = null;
    @Tag(tag=1308) public LuminanceStoneChallengeActivityDetailInfo luminanceStoneChallengeInfo = null;
    @Tag(tag=812) public RogueDiaryActivityDetailInfo rogueDiaryInfo = null;
    @Tag(tag=622) public SummerTimeV2DetailInfo summerTimeV2Info = null;
    @Tag(tag=1885) public IslandPartyDetailInfo islandPartyInfo = null;
    @Tag(tag=722) public GearActivityDetailInfo gearInfo = null;
    @Tag(tag=1911) public GravenInnocenceDetailInfo gravenInnocenceInfo = null;
    @Tag(tag=1043) public InstableSprayDetailInfo instableSprayInfo = null;
    @Tag(tag=1157) public MuqadasPotionActivityDetailInfo muqadasPotionInfo = null;
    @Tag(tag=966) public TreasureSeelieActivityDetailInfo treasureSeelieInfo = null;
    @Tag(tag=1078) public RockBoardExploreDetailInfo rockBoardExploreInfo = null;
    @Tag(tag=445) public VintageActivityDetailInfo vintageInfo = null;
    @Tag(tag=352) public WindFieldDetailInfo windFieldInfo = null;
    @Tag(tag=490) public FungusFighterDetailInfo fungusFighterInfo = null;
    @Tag(tag=1496) public CharAmusementDetailInfo charAmusementInfo = null;
    @Tag(tag=1025) public EffigyChallengeV2DetailInfo effigyChallengeInfo = null;
}
