package org.sorapointa.proto;
import io.github.sainttheana.proto.core.Tag;
import java.util.List;
import java.util.ArrayList;
import org.sorapointa.proto.TokenChange.*;
import org.sorapointa.proto.TokenChange;
import org.sorapointa.proto.PhaseChange.*;
import org.sorapointa.proto.PhaseChange;
import org.sorapointa.proto.AddCards.*;
import org.sorapointa.proto.AddCards;
import org.sorapointa.proto.RemoveCards.*;
import org.sorapointa.proto.RemoveCards;
import org.sorapointa.proto.SelectOnStage.*;
import org.sorapointa.proto.SelectOnStage;
import org.sorapointa.proto.DiceRoll.*;
import org.sorapointa.proto.DiceRoll;
import org.sorapointa.proto.DiceReroll.*;
import org.sorapointa.proto.DiceReroll;
import org.sorapointa.proto.Pass.*;
import org.sorapointa.proto.Pass;
import org.sorapointa.proto.CharDie.*;
import org.sorapointa.proto.CharDie;
import org.sorapointa.proto.SkillResult.*;
import org.sorapointa.proto.SkillResult;
import org.sorapointa.proto.CostDice.*;
import org.sorapointa.proto.CostDice;
import org.sorapointa.proto.AddDice.*;
import org.sorapointa.proto.AddDice;
import org.sorapointa.proto.MoveCard.*;
import org.sorapointa.proto.MoveCard;
import org.sorapointa.proto.UseSkill.*;
import org.sorapointa.proto.UseSkill;
import org.sorapointa.proto.NewCard.*;
import org.sorapointa.proto.NewCard;
import org.sorapointa.proto.UpdateController.*;
import org.sorapointa.proto.UpdateController;
import org.sorapointa.proto.ModifyAdd.*;
import org.sorapointa.proto.ModifyAdd;
import org.sorapointa.proto.ModifyRemove.*;
import org.sorapointa.proto.ModifyRemove;
import org.sorapointa.proto.UseSkillEnd.*;
import org.sorapointa.proto.UseSkillEnd;
import org.sorapointa.proto.DuelDataChange.*;
import org.sorapointa.proto.DuelDataChange;
import org.sorapointa.proto.ClientPerform.*;
import org.sorapointa.proto.ClientPerform;
import org.sorapointa.proto.GameOver.*;
import org.sorapointa.proto.GameOver;
import org.sorapointa.proto.OpTimer.*;
import org.sorapointa.proto.OpTimer;
import org.sorapointa.proto.WaitingListChange.*;
import org.sorapointa.proto.WaitingListChange;
import org.sorapointa.proto.CardUpdate.*;
import org.sorapointa.proto.CardUpdate;
import org.sorapointa.proto.SelectOnStageByEffect.*;
import org.sorapointa.proto.SelectOnStageByEffect;
import org.sorapointa.proto.CostRevise.*;
import org.sorapointa.proto.CostRevise;
import org.sorapointa.proto.PhaseContinue.*;
import org.sorapointa.proto.PhaseContinue;
import org.sorapointa.proto.PveIntentionInfo.*;
import org.sorapointa.proto.PveIntentionInfo;
import org.sorapointa.proto.PveIntentionChange.*;
import org.sorapointa.proto.PveIntentionChange;
import org.sorapointa.proto.SkillLimitsChange.*;
import org.sorapointa.proto.SkillLimitsChange;
import org.sorapointa.proto.NoDamageSkillResult.*;
import org.sorapointa.proto.NoDamageSkillResult;
import org.sorapointa.proto.ReactionBegin.*;
import org.sorapointa.proto.ReactionBegin;
import org.sorapointa.proto.ReactionEnd.*;
import org.sorapointa.proto.ReactionEnd;

public class GCGMessage {
    @Tag(tag=10) public TokenChange tokenChange = null;
    @Tag(tag=15) public PhaseChange phaseChange = null;
    @Tag(tag=11) public AddCards addCards = null;
    @Tag(tag=7) public RemoveCards removeCards = null;
    @Tag(tag=9) public SelectOnStage selectOnStage = null;
    @Tag(tag=3) public DiceRoll diceRoll = null;
    @Tag(tag=12) public DiceReroll diceReroll = null;
    @Tag(tag=5) public Pass pass = null;
    @Tag(tag=6) public CharDie charDie = null;
    @Tag(tag=1) public SkillResult skillResult = null;
    @Tag(tag=4) public CostDice costDice = null;
    @Tag(tag=13) public AddDice addDice = null;
    @Tag(tag=14) public MoveCard moveCard = null;
    @Tag(tag=2) public UseSkill useSkill = null;
    @Tag(tag=1658) public NewCard newCard = null;
    @Tag(tag=204) public UpdateController updateController = null;
    @Tag(tag=1001) public ModifyAdd modifyAdd = null;
    @Tag(tag=1447) public ModifyRemove modifyRemove = null;
    @Tag(tag=1779) public UseSkillEnd useSkillEnd = null;
    @Tag(tag=1102) public DuelDataChange duelDataChange = null;
    @Tag(tag=1225) public ClientPerform clientPerform = null;
    @Tag(tag=640) public GameOver gameOver = null;
    @Tag(tag=778) public OpTimer opTimer = null;
    @Tag(tag=517) public WaitingListChange waitingListChange = null;
    @Tag(tag=1284) public CardUpdate cardUpdate = null;
    @Tag(tag=542) public SelectOnStageByEffect selectOnStageByEffect = null;
    @Tag(tag=662) public CostRevise costRevise = null;
    @Tag(tag=344) public PhaseContinue phaseContinue = null;
    @Tag(tag=975) public PveIntentionInfo pveIntentionInfo = null;
    @Tag(tag=719) public PveIntentionChange pveIntentionChange = null;
    @Tag(tag=597) public SkillLimitsChange skillLimitsChange = null;
    @Tag(tag=1483) public NoDamageSkillResult noDamageSkillResult = null;
    @Tag(tag=170) public ReactionBegin reactionBegin = null;
    @Tag(tag=58) public ReactionEnd reactionEnd = null;
}
