package org.sorapointa.proto;
import io.github.sainttheana.proto.core.Tag;
import java.util.List;
import java.util.ArrayList;
import org.sorapointa.proto.GCGMsgAddCards.*;
import org.sorapointa.proto.GCGMsgAddCards;
import org.sorapointa.proto.GCGMsgAddDice.*;
import org.sorapointa.proto.GCGMsgAddDice;
import org.sorapointa.proto.GCGMsgCardUpdate.*;
import org.sorapointa.proto.GCGMsgCardUpdate;
import org.sorapointa.proto.GCGMsgCharDie.*;
import org.sorapointa.proto.GCGMsgCharDie;
import org.sorapointa.proto.GCGMsgClientPerform.*;
import org.sorapointa.proto.GCGMsgClientPerform;
import org.sorapointa.proto.GCGMsgCostDice.*;
import org.sorapointa.proto.GCGMsgCostDice;
import org.sorapointa.proto.GCGMsgCostRevise.*;
import org.sorapointa.proto.GCGMsgCostRevise;
import org.sorapointa.proto.GCGMsgDiceReroll.*;
import org.sorapointa.proto.GCGMsgDiceReroll;
import org.sorapointa.proto.GCGMsgDiceRoll.*;
import org.sorapointa.proto.GCGMsgDiceRoll;
import org.sorapointa.proto.GCGMsgDuelDataChange.*;
import org.sorapointa.proto.GCGMsgDuelDataChange;
import org.sorapointa.proto.GCGMsgGameOver.*;
import org.sorapointa.proto.GCGMsgGameOver;
import org.sorapointa.proto.GCGMsgModifyAdd.*;
import org.sorapointa.proto.GCGMsgModifyAdd;
import org.sorapointa.proto.GCGMsgModifyRemove.*;
import org.sorapointa.proto.GCGMsgModifyRemove;
import org.sorapointa.proto.GCGMsgMoveCard.*;
import org.sorapointa.proto.GCGMsgMoveCard;
import org.sorapointa.proto.GCGMsgNewCard.*;
import org.sorapointa.proto.GCGMsgNewCard;
import org.sorapointa.proto.GCGMsgOpTimer.*;
import org.sorapointa.proto.GCGMsgOpTimer;
import org.sorapointa.proto.GCGMsgPVEDoOp.*;
import org.sorapointa.proto.GCGMsgPVEDoOp;
import org.sorapointa.proto.GCGMsgPVEGenCardOp.*;
import org.sorapointa.proto.GCGMsgPVEGenCardOp;
import org.sorapointa.proto.GCGMsgPass.*;
import org.sorapointa.proto.GCGMsgPass;
import org.sorapointa.proto.GCGMsgPhaseChange.*;
import org.sorapointa.proto.GCGMsgPhaseChange;
import org.sorapointa.proto.GCGMsgRemoveCards.*;
import org.sorapointa.proto.GCGMsgRemoveCards;
import org.sorapointa.proto.GCGMsgSelectOnStage.*;
import org.sorapointa.proto.GCGMsgSelectOnStage;
import org.sorapointa.proto.GCGMsgSelectOnStageByEffect.*;
import org.sorapointa.proto.GCGMsgSelectOnStageByEffect;
import org.sorapointa.proto.GCGMsgSkillResult.*;
import org.sorapointa.proto.GCGMsgSkillResult;
import org.sorapointa.proto.GCGMsgTokenChange.*;
import org.sorapointa.proto.GCGMsgTokenChange;
import org.sorapointa.proto.GCGMsgUpdateController.*;
import org.sorapointa.proto.GCGMsgUpdateController;
import org.sorapointa.proto.GCGMsgUseSkill.*;
import org.sorapointa.proto.GCGMsgUseSkill;
import org.sorapointa.proto.GCGMsgUseSkillEnd.*;
import org.sorapointa.proto.GCGMsgUseSkillEnd;
import org.sorapointa.proto.GCGMsgWaitingListChange.*;
import org.sorapointa.proto.GCGMsgWaitingListChange;

public class GCGMessage {
    @Tag(tag=12) public GCGMsgTokenChange tokenChange = null;
    @Tag(tag=13) public GCGMsgPhaseChange phaseChange = null;
    @Tag(tag=10) public GCGMsgAddCards addCards = null;
    @Tag(tag=14) public GCGMsgRemoveCards removeCards = null;
    @Tag(tag=6) public GCGMsgSelectOnStage selectOnStage = null;
    @Tag(tag=9) public GCGMsgDiceRoll diceRoll = null;
    @Tag(tag=11) public GCGMsgDiceReroll diceReroll = null;
    @Tag(tag=5) public GCGMsgPass pass = null;
    @Tag(tag=2) public GCGMsgCharDie charDie = null;
    @Tag(tag=1) public GCGMsgSkillResult skillResult = null;
    @Tag(tag=7) public GCGMsgCostDice costDice = null;
    @Tag(tag=3) public GCGMsgAddDice addDice = null;
    @Tag(tag=15) public GCGMsgMoveCard moveCard = null;
    @Tag(tag=4) public GCGMsgUseSkill useSkill = null;
    @Tag(tag=1848) public GCGMsgNewCard newCard = null;
    @Tag(tag=429) public GCGMsgUpdateController updateController = null;
    @Tag(tag=1851) public GCGMsgModifyAdd modifyAdd = null;
    @Tag(tag=471) public GCGMsgModifyRemove modifyRemove = null;
    @Tag(tag=1411) public GCGMsgUseSkillEnd useSkillEnd = null;
    @Tag(tag=1741) public GCGMsgPVEGenCardOp pveGenCardOp = null;
    @Tag(tag=614) public GCGMsgPVEDoOp pveDoOp = null;
    @Tag(tag=1008) public GCGMsgDuelDataChange duelDataChange = null;
    @Tag(tag=1035) public GCGMsgClientPerform clientPerform = null;
    @Tag(tag=714) public GCGMsgGameOver gameOver = null;
    @Tag(tag=1862) public GCGMsgOpTimer opTimer = null;
    @Tag(tag=1678) public GCGMsgWaitingListChange waitingListChange = null;
    @Tag(tag=1879) public GCGMsgCardUpdate cardUpdate = null;
    @Tag(tag=2042) public GCGMsgSelectOnStageByEffect selectOnStageByEffect = null;
    @Tag(tag=1350) public GCGMsgCostRevise costRevise = null;
}
