package org.sorapointa.proto;
import io.github.sainttheana.proto.core.Tag;
import java.util.List;
import java.util.ArrayList;

public enum MotionState {
        @Tag(tag=0) MOTION_STATE_NONE ,
        @Tag(tag=1) MOTION_STATE_RESET ,
        @Tag(tag=2) MOTION_STATE_STANDBY ,
        @Tag(tag=3) MOTION_STATE_STANDBY_MOVE ,
        @Tag(tag=4) MOTION_STATE_WALK ,
        @Tag(tag=5) MOTION_STATE_RUN ,
        @Tag(tag=6) MOTION_STATE_DASH ,
        @Tag(tag=7) MOTION_STATE_CLIMB ,
        @Tag(tag=8) MOTION_STATE_CLIMB_JUMP ,
        @Tag(tag=9) MOTION_STATE_STANDBY_TO_CLIMB ,
        @Tag(tag=10) MOTION_STATE_FIGHT ,
        @Tag(tag=11) MOTION_STATE_JUMP ,
        @Tag(tag=12) MOTION_STATE_DROP ,
        @Tag(tag=13) MOTION_STATE_FLY ,
        @Tag(tag=14) MOTION_STATE_SWIM_MOVE ,
        @Tag(tag=15) MOTION_STATE_SWIM_IDLE ,
        @Tag(tag=16) MOTION_STATE_SWIM_DASH ,
        @Tag(tag=17) MOTION_STATE_SWIM_JUMP ,
        @Tag(tag=18) MOTION_STATE_SLIP ,
        @Tag(tag=19) MOTION_STATE_GO_UPSTAIRS ,
        @Tag(tag=20) MOTION_STATE_FALL_ON_GROUND ,
        @Tag(tag=21) MOTION_STATE_JUMP_UP_WALL_FOR_STANDBY ,
        @Tag(tag=22) MOTION_STATE_JUMP_OFF_WALL ,
        @Tag(tag=23) MOTION_STATE_POWERED_FLY ,
        @Tag(tag=24) MOTION_STATE_LADDER_IDLE ,
        @Tag(tag=25) MOTION_STATE_LADDER_MOVE ,
        @Tag(tag=26) MOTION_STATE_LADDER_SLIP ,
        @Tag(tag=27) MOTION_STATE_STANDBY_TO_LADDER ,
        @Tag(tag=28) MOTION_STATE_LADDER_TO_STANDBY ,
        @Tag(tag=29) MOTION_STATE_DANGER_STANDBY ,
        @Tag(tag=30) MOTION_STATE_DANGER_STANDBY_MOVE ,
        @Tag(tag=31) MOTION_STATE_DANGER_WALK ,
        @Tag(tag=32) MOTION_STATE_DANGER_RUN ,
        @Tag(tag=33) MOTION_STATE_DANGER_DASH ,
        @Tag(tag=34) MOTION_STATE_CROUCH_IDLE ,
        @Tag(tag=35) MOTION_STATE_CROUCH_MOVE ,
        @Tag(tag=36) MOTION_STATE_CROUCH_ROLL ,
        @Tag(tag=37) MOTION_STATE_NOTIFY ,
        @Tag(tag=38) MOTION_STATE_LAND_SPEED ,
        @Tag(tag=39) MOTION_STATE_MOVE_FAIL_ACK ,
        @Tag(tag=40) MOTION_STATE_WATERFALL ,
        @Tag(tag=41) MOTION_STATE_DASH_BEFORE_SHAKE ,
        @Tag(tag=42) MOTION_STATE_SIT_IDLE ,
        @Tag(tag=43) MOTION_STATE_FORCE_SET_POS ,
        @Tag(tag=44) MOTION_STATE_QUEST_FORCE_DRAG ,
        @Tag(tag=45) MOTION_STATE_FOLLOW_ROUTE ,
        @Tag(tag=46) MOTION_STATE_SKIFF_BOARDING ,
        @Tag(tag=47) MOTION_STATE_SKIFF_NORMAL ,
        @Tag(tag=48) MOTION_STATE_SKIFF_DASH ,
        @Tag(tag=49) MOTION_STATE_SKIFF_POWERED_DASH ,
        @Tag(tag=50) MOTION_STATE_DESTROY_VEHICLE ,
        @Tag(tag=51) MOTION_STATE_FLY_IDLE ,
        @Tag(tag=52) MOTION_STATE_FLY_SLOW ,
        @Tag(tag=53) MOTION_STATE_FLY_FAST ,
        @Tag(tag=54) MOTION_STATE_AIM_MOVE ,
        @Tag(tag=55) MOTION_STATE_AIR_COMPENSATION ,
        @Tag(tag=56) MOTION_STATE_NUM ;
}
