package org.sorapointa.proto;
import io.github.sainttheana.proto.core.Tag;
import java.util.List;
import java.util.ArrayList;
import org.sorapointa.proto.AdjustTrackingInfo.*;
import org.sorapointa.proto.AdjustTrackingInfo;
import org.sorapointa.proto.TrackingIOInfo.*;
import org.sorapointa.proto.TrackingIOInfo;

public class PlayerLoginReq {
    @Tag(tag=6) public Integer languageType = null;
    @Tag(tag=615) public Integer regPlatform = null;
    @Tag(tag=1660) public TrackingIOInfo trackingIoInfo = null;
    @Tag(tag=13) public Integer accountType = null;
    @Tag(tag=15) public String token = null;
    @Tag(tag=1458) public byte[] extraBinData = null;
    @Tag(tag=1314) public Integer channelId = null;
    @Tag(tag=688) public Integer clientDataVersion = null;
    @Tag(tag=2) public String accountUid = null;
    @Tag(tag=12) public String clientVersion = null;
    @Tag(tag=772) public String securityLibraryMd5 = null;
    @Tag(tag=2000) public String countryCode = null;
    @Tag(tag=1268) public String psnId = null;
    @Tag(tag=431) public Integer clientPort = null;
    @Tag(tag=9) public String deviceName = null;
    @Tag(tag=1163) public String cps = null;
    @Tag(tag=3) public Long loginRand = null;
    @Tag(tag=984) public Integer targetHomeParam = null;
    @Tag(tag=1816) public AdjustTrackingInfo adjustTrackingInfo = null;
    @Tag(tag=908) public Boolean isTransfer = null;
    @Tag(tag=1787) public Integer tag = null;
    @Tag(tag=5) public Boolean isGuest = null;
    @Tag(tag=2026) public byte[] environmentErrorCode = null;
    @Tag(tag=903) public String onlineId = null;
    @Tag(tag=8) public Boolean isEditor = null;
    @Tag(tag=861) public String checksumClientVersion = null;
    @Tag(tag=1995) public byte[] securityCmdReply = null;
    @Tag(tag=1213) public String securityLibraryVersion = null;
    @Tag(tag=1652) public String birthday = null;
    @Tag(tag=4) public String deviceUuid = null;
    @Tag(tag=1546) public Integer clientToken = null;
    @Tag(tag=23) public Integer subChannelId = null;
    @Tag(tag=11) public Integer targetUid = null;
    @Tag(tag=1) public String deviceInfo = null;
    @Tag(tag=1707) public String clientVerisonHash = null;
    @Tag(tag=1532) public String checksum = null;
    @Tag(tag=14) public Integer platformType = null;
    @Tag(tag=1864) public Integer targetHomeOwnerUid = null;
    @Tag(tag=1335) public Integer cloudClientIp = null;
    @Tag(tag=612) public Integer gmUid = null;
    @Tag(tag=10) public String systemVersion = null;
    @Tag(tag=7) public String platform = null;
}
