package org.sorapointa.proto;
import io.github.sainttheana.proto.core.Tag;
import java.util.List;
import java.util.ArrayList;
import org.sorapointa.proto.GalleryStageType.*;
import org.sorapointa.proto.GalleryStageType;
import org.sorapointa.proto.SceneGalleryBalloonInfo.*;
import org.sorapointa.proto.SceneGalleryBalloonInfo;
import org.sorapointa.proto.SceneGalleryBounceConjuringInfo.*;
import org.sorapointa.proto.SceneGalleryBounceConjuringInfo;
import org.sorapointa.proto.SceneGalleryBrokenFloorInfo.*;
import org.sorapointa.proto.SceneGalleryBrokenFloorInfo;
import org.sorapointa.proto.SceneGalleryBulletInfo.*;
import org.sorapointa.proto.SceneGalleryBulletInfo;
import org.sorapointa.proto.SceneGalleryBuoyantCombatInfo.*;
import org.sorapointa.proto.SceneGalleryBuoyantCombatInfo;
import org.sorapointa.proto.SceneGalleryCharAmusementInfo.*;
import org.sorapointa.proto.SceneGalleryCharAmusementInfo;
import org.sorapointa.proto.SceneGalleryCrystalLinkInfo.*;
import org.sorapointa.proto.SceneGalleryCrystalLinkInfo;
import org.sorapointa.proto.SceneGalleryEffigyChallengeV2Info.*;
import org.sorapointa.proto.SceneGalleryEffigyChallengeV2Info;
import org.sorapointa.proto.SceneGalleryFallInfo.*;
import org.sorapointa.proto.SceneGalleryFallInfo;
import org.sorapointa.proto.SceneGalleryFlowerInfo.*;
import org.sorapointa.proto.SceneGalleryFlowerInfo;
import org.sorapointa.proto.SceneGalleryFungusFighterCaptureInfo.*;
import org.sorapointa.proto.SceneGalleryFungusFighterCaptureInfo;
import org.sorapointa.proto.SceneGalleryFungusFighterTrainingInfo.*;
import org.sorapointa.proto.SceneGalleryFungusFighterTrainingInfo;
import org.sorapointa.proto.SceneGalleryHandballInfo.*;
import org.sorapointa.proto.SceneGalleryHandballInfo;
import org.sorapointa.proto.SceneGalleryHideAndSeekInfo.*;
import org.sorapointa.proto.SceneGalleryHideAndSeekInfo;
import org.sorapointa.proto.SceneGalleryHomeBalloonInfo.*;
import org.sorapointa.proto.SceneGalleryHomeBalloonInfo;
import org.sorapointa.proto.SceneGalleryHomeSeekFurnitureInfo.*;
import org.sorapointa.proto.SceneGalleryHomeSeekFurnitureInfo;
import org.sorapointa.proto.SceneGalleryInstableSprayInfo.*;
import org.sorapointa.proto.SceneGalleryInstableSprayInfo;
import org.sorapointa.proto.SceneGalleryIrodoriMasterInfo.*;
import org.sorapointa.proto.SceneGalleryIrodoriMasterInfo;
import org.sorapointa.proto.SceneGalleryIslandPartyDownHillInfo.*;
import org.sorapointa.proto.SceneGalleryIslandPartyDownHillInfo;
import org.sorapointa.proto.SceneGalleryIslandPartyRaftInfo.*;
import org.sorapointa.proto.SceneGalleryIslandPartyRaftInfo;
import org.sorapointa.proto.SceneGalleryIslandPartySailInfo.*;
import org.sorapointa.proto.SceneGalleryIslandPartySailInfo;
import org.sorapointa.proto.SceneGalleryLuminanceStoneChallengeInfo.*;
import org.sorapointa.proto.SceneGalleryLuminanceStoneChallengeInfo;
import org.sorapointa.proto.SceneGalleryMuqadasPotionInfo.*;
import org.sorapointa.proto.SceneGalleryMuqadasPotionInfo;
import org.sorapointa.proto.SceneGalleryProgressInfo.*;
import org.sorapointa.proto.SceneGalleryProgressInfo;
import org.sorapointa.proto.SceneGallerySalvageEscortInfo.*;
import org.sorapointa.proto.SceneGallerySalvageEscortInfo;
import org.sorapointa.proto.SceneGallerySalvagePreventInfo.*;
import org.sorapointa.proto.SceneGallerySalvagePreventInfo;
import org.sorapointa.proto.SceneGallerySummerTimeV2BoatInfo.*;
import org.sorapointa.proto.SceneGallerySummerTimeV2BoatInfo;
import org.sorapointa.proto.SceneGallerySumoInfo.*;
import org.sorapointa.proto.SceneGallerySumoInfo;
import org.sorapointa.proto.SceneGalleryTreasureSeelieInfo.*;
import org.sorapointa.proto.SceneGalleryTreasureSeelieInfo;
import org.sorapointa.proto.SceneGalleryVintageHuntingInfo.*;
import org.sorapointa.proto.SceneGalleryVintageHuntingInfo;
import org.sorapointa.proto.SceneGalleryWindFieldInfo.*;
import org.sorapointa.proto.SceneGalleryWindFieldInfo;

public class SceneGalleryInfo {
    @Tag(tag=5) public Integer stage = null;
    @Tag(tag=4) public List<SceneGalleryProgressInfo> progressInfoList = new ArrayList<>();
    @Tag(tag=2) public Integer galleryId = null;
    @Tag(tag=3) public Integer startTime = null;
    @Tag(tag=11) public Integer endTime = null;
    @Tag(tag=9) public Integer ownerUid = null;
    @Tag(tag=1) public Integer playerCount = null;
    @Tag(tag=15) public Integer preStartEndTime = null;
    @Tag(tag=14) public SceneGalleryBalloonInfo balloonInfo = null;
    @Tag(tag=7) public SceneGalleryFallInfo fallInfo = null;
    @Tag(tag=8) public SceneGalleryFlowerInfo flowerInfo = null;
    @Tag(tag=13) public SceneGalleryBulletInfo bulletInfo = null;
    @Tag(tag=10) public SceneGalleryBrokenFloorInfo brokenFloorInfo = null;
    @Tag(tag=6) public SceneGalleryHideAndSeekInfo hideAndSeekInfo = null;
    @Tag(tag=1384) public SceneGalleryBuoyantCombatInfo buoyantCombatInfo = null;
    @Tag(tag=708) public SceneGalleryBounceConjuringInfo bounceConjuringInfo = null;
    @Tag(tag=1997) public SceneGalleryHandballInfo handballInfo = null;
    @Tag(tag=811) public SceneGallerySumoInfo sumoInfo = null;
    @Tag(tag=1700) public SceneGallerySalvagePreventInfo salvagePreventInfo = null;
    @Tag(tag=759) public SceneGallerySalvageEscortInfo salvageEscortInfo = null;
    @Tag(tag=1034) public SceneGalleryHomeBalloonInfo homeBalloonInfo = null;
    @Tag(tag=2004) public SceneGalleryCrystalLinkInfo crystalLinkInfo = null;
    @Tag(tag=1953) public SceneGalleryIrodoriMasterInfo irodoriMasterInfo = null;
    @Tag(tag=106) public SceneGalleryLuminanceStoneChallengeInfo luminanceStoneChallengeInfo = null;
    @Tag(tag=1456) public SceneGalleryHomeSeekFurnitureInfo homeSeekFurnitureInfo = null;
    @Tag(tag=462) public SceneGalleryIslandPartyDownHillInfo islandPartyDownHillInfo = null;
    @Tag(tag=296) public SceneGallerySummerTimeV2BoatInfo summerTimeV2BoatInfo = null;
    @Tag(tag=1805) public SceneGalleryIslandPartyRaftInfo islandPartyRaftInfo = null;
    @Tag(tag=1133) public SceneGalleryIslandPartySailInfo islandPartySailInfo = null;
    @Tag(tag=1196) public SceneGalleryInstableSprayInfo instableSprayInfo = null;
    @Tag(tag=865) public SceneGalleryMuqadasPotionInfo muqadasPotionInfo = null;
    @Tag(tag=1525) public SceneGalleryTreasureSeelieInfo treasureSeelieInfo = null;
    @Tag(tag=254) public SceneGalleryVintageHuntingInfo vintageHuntingInfo = null;
    @Tag(tag=1080) public SceneGalleryWindFieldInfo windFieldInfo = null;
    @Tag(tag=1328) public SceneGalleryFungusFighterTrainingInfo fungusFighterTrainingInfo = null;
    @Tag(tag=882) public SceneGalleryEffigyChallengeV2Info effigyChallengeInfo = null;
    @Tag(tag=422) public SceneGalleryFungusFighterCaptureInfo fungusFighterCaptureInfo = null;
    @Tag(tag=1086) public SceneGalleryCharAmusementInfo charAmusementInfo = null;
}
