package org.sorapointa.proto;
import io.github.sainttheana.proto.core.Tag;
import java.util.List;
import java.util.ArrayList;
import org.sorapointa.proto.BalloonInfo.*;
import org.sorapointa.proto.BalloonInfo;
import org.sorapointa.proto.FallInfo.*;
import org.sorapointa.proto.FallInfo;
import org.sorapointa.proto.FlowerInfo.*;
import org.sorapointa.proto.FlowerInfo;
import org.sorapointa.proto.BulletInfo.*;
import org.sorapointa.proto.BulletInfo;
import org.sorapointa.proto.BrokenFloorInfo.*;
import org.sorapointa.proto.BrokenFloorInfo;
import org.sorapointa.proto.HideAndSeekInfo.*;
import org.sorapointa.proto.HideAndSeekInfo;
import org.sorapointa.proto.BuoyantCombatInfo.*;
import org.sorapointa.proto.BuoyantCombatInfo;
import org.sorapointa.proto.BounceConjuringInfo.*;
import org.sorapointa.proto.BounceConjuringInfo;
import org.sorapointa.proto.HandballInfo.*;
import org.sorapointa.proto.HandballInfo;
import org.sorapointa.proto.SumoInfo.*;
import org.sorapointa.proto.SumoInfo;
import org.sorapointa.proto.SalvagePreventInfo.*;
import org.sorapointa.proto.SalvagePreventInfo;
import org.sorapointa.proto.SalvageEscortInfo.*;
import org.sorapointa.proto.SalvageEscortInfo;
import org.sorapointa.proto.HomeBalloonInfo.*;
import org.sorapointa.proto.HomeBalloonInfo;
import org.sorapointa.proto.CrystalLinkInfo.*;
import org.sorapointa.proto.CrystalLinkInfo;
import org.sorapointa.proto.IrodoriMasterInfo.*;
import org.sorapointa.proto.IrodoriMasterInfo;
import org.sorapointa.proto.LuminanceStoneChallengeInfo.*;
import org.sorapointa.proto.LuminanceStoneChallengeInfo;
import org.sorapointa.proto.HomeSeekFurnitureInfo.*;
import org.sorapointa.proto.HomeSeekFurnitureInfo;
import org.sorapointa.proto.IslandPartyDownHillInfo.*;
import org.sorapointa.proto.IslandPartyDownHillInfo;
import org.sorapointa.proto.SummerTimeV2BoatInfo.*;
import org.sorapointa.proto.SummerTimeV2BoatInfo;
import org.sorapointa.proto.IslandPartyRaftInfo.*;
import org.sorapointa.proto.IslandPartyRaftInfo;
import org.sorapointa.proto.IslandPartySailInfo.*;
import org.sorapointa.proto.IslandPartySailInfo;
import org.sorapointa.proto.InstableSprayInfo.*;
import org.sorapointa.proto.InstableSprayInfo;
import org.sorapointa.proto.MuqadasPotionInfo.*;
import org.sorapointa.proto.MuqadasPotionInfo;
import org.sorapointa.proto.TreasureSeelieInfo.*;
import org.sorapointa.proto.TreasureSeelieInfo;
import org.sorapointa.proto.VintageHuntingInfo.*;
import org.sorapointa.proto.VintageHuntingInfo;
import org.sorapointa.proto.WindFieldInfo.*;
import org.sorapointa.proto.WindFieldInfo;
import org.sorapointa.proto.FungusFighterTrainingInfo.*;
import org.sorapointa.proto.FungusFighterTrainingInfo;
import org.sorapointa.proto.EffigyChallengeInfo.*;
import org.sorapointa.proto.EffigyChallengeInfo;
import org.sorapointa.proto.FungusFighterCaptureInfo.*;
import org.sorapointa.proto.FungusFighterCaptureInfo;
import org.sorapointa.proto.CharAmusementInfo.*;
import org.sorapointa.proto.CharAmusementInfo;
import org.sorapointa.proto.CoinCollectInfo.*;
import org.sorapointa.proto.CoinCollectInfo;
import org.sorapointa.proto.TeamChainInfo.*;
import org.sorapointa.proto.TeamChainInfo;
import org.sorapointa.proto.DuelHeartInfo.*;
import org.sorapointa.proto.DuelHeartInfo;
import org.sorapointa.proto.BoatMultiInfo.*;
import org.sorapointa.proto.BoatMultiInfo;
import org.sorapointa.proto.GalleryStageType.*;
import org.sorapointa.proto.GalleryStageType;
import org.sorapointa.proto.SceneGalleryProgressInfo.*;
import org.sorapointa.proto.SceneGalleryProgressInfo;

public class SceneGalleryInfo {
    @Tag(tag=15) public Integer endTime = null;
    @Tag(tag=5) public Integer startTime = null;
    @Tag(tag=14) public BalloonInfo balloonInfo = null;
    @Tag(tag=1) public FallInfo fallInfo = null;
    @Tag(tag=6) public FlowerInfo flowerInfo = null;
    @Tag(tag=10) public BulletInfo bulletInfo = null;
    @Tag(tag=9) public BrokenFloorInfo brokenFloorInfo = null;
    @Tag(tag=13) public HideAndSeekInfo hideAndSeekInfo = null;
    @Tag(tag=461) public BuoyantCombatInfo buoyantCombatInfo = null;
    @Tag(tag=403) public BounceConjuringInfo bounceConjuringInfo = null;
    @Tag(tag=1637) public HandballInfo handballInfo = null;
    @Tag(tag=1000) public SumoInfo sumoInfo = null;
    @Tag(tag=521) public SalvagePreventInfo salvagePreventInfo = null;
    @Tag(tag=33) public SalvageEscortInfo salvageEscortInfo = null;
    @Tag(tag=1858) public HomeBalloonInfo homeBalloonInfo = null;
    @Tag(tag=177) public CrystalLinkInfo crystalLinkInfo = null;
    @Tag(tag=1317) public IrodoriMasterInfo irodoriMasterInfo = null;
    @Tag(tag=401) public LuminanceStoneChallengeInfo luminanceStoneChallengeInfo = null;
    @Tag(tag=530) public HomeSeekFurnitureInfo homeSeekFurnitureInfo = null;
    @Tag(tag=1026) public IslandPartyDownHillInfo islandPartyDownHillInfo = null;
    @Tag(tag=1460) public SummerTimeV2BoatInfo summerTimeV2boatInfo = null;
    @Tag(tag=294) public IslandPartyRaftInfo islandPartyRaftInfo = null;
    @Tag(tag=592) public IslandPartySailInfo islandPartySailInfo = null;
    @Tag(tag=127) public InstableSprayInfo instableSprayInfo = null;
    @Tag(tag=615) public MuqadasPotionInfo muqadasPotionInfo = null;
    @Tag(tag=1420) public TreasureSeelieInfo treasureSeelieInfo = null;
    @Tag(tag=1361) public VintageHuntingInfo vintageHuntingInfo = null;
    @Tag(tag=1448) public WindFieldInfo windFieldInfo = null;
    @Tag(tag=291) public FungusFighterTrainingInfo fungusFighterTrainingInfo = null;
    @Tag(tag=290) public EffigyChallengeInfo effigyChallengeInfo = null;
    @Tag(tag=1362) public FungusFighterCaptureInfo fungusFighterCaptureInfo = null;
    @Tag(tag=1649) public CharAmusementInfo charAmusementInfo = null;
    @Tag(tag=963) public CoinCollectInfo coinCollectInfo = null;
    @Tag(tag=990) public TeamChainInfo teamChainInfo = null;
    @Tag(tag=789) public DuelHeartInfo duelHeartInfo = null;
    @Tag(tag=1222) public BoatMultiInfo boatMultiInfo = null;
    @Tag(tag=2) public Integer stage = null;
    @Tag(tag=7) public Integer ownerUid = null;
    @Tag(tag=3) public Integer galleryId = null;
    @Tag(tag=8) public Integer preStartEndTime = null;
    @Tag(tag=11) public Integer playerCount = null;
    @Tag(tag=12) public List<SceneGalleryProgressInfo> progressInfoList = new ArrayList<>();
}
